# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kylinbot_core/CBUS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CBUS(genpy.Message):
  _md5sum = "93fce3d0dc3169a0815342b4ce4be9c7"
  _type = "kylinbot_core/CBUS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 fs
int16 px
int16 py
int16 pz
int16 pe
int16 pc
int16 vx
int16 vy
int16 vz
int16 ve
int16 vc
"""
  __slots__ = ['fs','px','py','pz','pe','pc','vx','vy','vz','ve','vc']
  _slot_types = ['uint32','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fs,px,py,pz,pe,pc,vx,vy,vz,ve,vc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CBUS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fs is None:
        self.fs = 0
      if self.px is None:
        self.px = 0
      if self.py is None:
        self.py = 0
      if self.pz is None:
        self.pz = 0
      if self.pe is None:
        self.pe = 0
      if self.pc is None:
        self.pc = 0
      if self.vx is None:
        self.vx = 0
      if self.vy is None:
        self.vy = 0
      if self.vz is None:
        self.vz = 0
      if self.ve is None:
        self.ve = 0
      if self.vc is None:
        self.vc = 0
    else:
      self.fs = 0
      self.px = 0
      self.py = 0
      self.pz = 0
      self.pe = 0
      self.pc = 0
      self.vx = 0
      self.vy = 0
      self.vz = 0
      self.ve = 0
      self.vc = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_I10h.pack(_x.fs, _x.px, _x.py, _x.pz, _x.pe, _x.pc, _x.vx, _x.vy, _x.vz, _x.ve, _x.vc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.fs, _x.px, _x.py, _x.pz, _x.pe, _x.pc, _x.vx, _x.vy, _x.vz, _x.ve, _x.vc,) = _struct_I10h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_I10h.pack(_x.fs, _x.px, _x.py, _x.pz, _x.pe, _x.pc, _x.vx, _x.vy, _x.vz, _x.ve, _x.vc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.fs, _x.px, _x.py, _x.pz, _x.pe, _x.pc, _x.vx, _x.vy, _x.vz, _x.ve, _x.vc,) = _struct_I10h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_I10h = struct.Struct("<I10h")
